### ISSUE TITLE
澎湃OS bug反馈

### ISSUE THREAD

**Issue by dandandedd** [coolight7/MimicryMusic#51]
系统 澎湃os 安卓14
在后台多任务界面划掉拟声会使《三方应用异常分析》报告：拟声因自身原因问题造成闪退
报错信息如下：
应用名称：拟声
应用版本：0.30.0
问题发生时间：2024-06-16
k5.g: An operation is not implemented: Not yet implemented
	at o6.a.onDetachedFromActivity(Unknown Source:21)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(Unknown Source:34)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(Unknown Source:63)
	at io.flutter.embedding.android.FlutterActivity.onDestroy(Unknown Source:18)
	at android.app.Activity.performDestroy(Activity.java:9190)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1505)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5913)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5958)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

**Comment by coolight7** [comment]
> 其实解决办法是把三方应用分析卸载就好了，手动清理和闪退没啥区别qaq

哈哈
